/**
 * JLPT level lookup — Issue #3.
 *
 * Provides a fast synchronous lookup of a word's JLPT level (N1–N5) from a
 * compact bundled JSON map.  No network call is needed; the data is imported
 * at build time and lives in the extension bundle.
 *
 * Data source: community JLPT word lists compiled from Jonathan Waller's
 * jlpt.info data (free for any use).  The bundled JSON is regenerated by
 * running `node scripts/generate-jlpt-data.mjs` from the project root.
 *
 * @example
 *   lookupJlpt('食べる') // → 'N5'
 *   lookupJlpt('渾然一体') // → 'N1'
 *   lookupJlpt('クリスマス') // → null (not in any list)
 */

import jlptMap from '../data/jlpt-data.json';

type JlptLevel = 'N1' | 'N2' | 'N3' | 'N4' | 'N5';

// The JSON file is a plain { [word: string]: JlptLevel } object.
// TypeScript infers it as `{ [key: string]: string }` from the JSON import, so
// we cast to the narrower type once here.
const JLPT_MAP = jlptMap as Record<string, JlptLevel>;

/**
 * Look up the JLPT level for a word.
 *
 * Returns the level string ('N1'–'N5') if the word appears in the bundled
 * JLPT word list, or `null` if the word is not found in any level.
 *
 * The lookup is O(1) — a plain property access on an in-memory object.
 *
 * @param word  The Japanese word to look up (kanji, kana, or mixed form).
 */
export function lookupJlpt(word: string): JlptLevel | null {
  return JLPT_MAP[word] ?? null;
}
